server:
  port: 8080
  encoding:
    charset: UTF-8
    force-response: true
spring:
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kte_labs?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: innodb
        format_sql: true
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
